USE [master]
GO

/****** Object:  Database [WAPI_DB]    Script Date: 2/23/2017 9:03:34 PM ******/
CREATE DATABASE [WAPI_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WAPI_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\WAPI_DB.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WAPI_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\WAPI_DB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [WAPI_DB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WAPI_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WAPI_DB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WAPI_DB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WAPI_DB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WAPI_DB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WAPI_DB] SET ARITHABORT OFF 
GO

ALTER DATABASE [WAPI_DB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WAPI_DB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WAPI_DB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WAPI_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WAPI_DB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WAPI_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WAPI_DB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WAPI_DB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WAPI_DB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WAPI_DB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WAPI_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WAPI_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WAPI_DB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WAPI_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WAPI_DB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WAPI_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WAPI_DB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WAPI_DB] SET RECOVERY FULL 
GO

ALTER DATABASE [WAPI_DB] SET  MULTI_USER 
GO

ALTER DATABASE [WAPI_DB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WAPI_DB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WAPI_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WAPI_DB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [WAPI_DB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WAPI_DB] SET  READ_WRITE 
GO

